### ISSUE TITLE
Using python setup instead of pip

### ISSUE THREAD

**Issue by carneirofc** [lnls-sirius/lnls-ansible#128]
* Is there any reason to not use pip to install packages in the Makefile target? 
* How the uninstall steps are being handled? Using `python ./setup.py install` we have to keep track of the changes and manually undo them if needed.

If directly using `setup.py` is required for something else that I'm missing, how about we save the changes and add an uninstall target? For example:

```
install: clean-git
	sudo ./setup.py install --single-version-externally-managed --compile --force --record changes.txt

uninstall:
	xargs rm -vrf < changes.txt
```

**Comment by lerwys** [comment]
Hi @carneirofc 

Which role or package is this?

**Comment by carneirofc** [comment]
I'm realising that this isn't the best place to raise this issue. I'm referring to the content of the [siriushla](https://github.com/lnls-sirius/hla/blob/master/pyqt-apps/Makefile) and [siriushlacon](https://github.com/lnls-sirius/pydm-opi/blob/master/Makefile) Makefiles.

**Comment by lerwys** [comment]
Oh ok. I think it's best to open new issues on those repositories then.

Side question. We do we need to call the `clean` or `clean-git` targets on a `install` target? @xresende explained it to me before, but I keep forgetting. The `install` target, in my opinion, should never remove things from the repository.
