### ISSUE TITLE
Add octave and mca to desktop-apps

### ISSUE THREAD

**Issue by lerwys** [lnls-sirius/lnls-ansible#20]
**Problem:** @danielot has asked for octave and EPICS mca packages to be installed at the control room computers. Would that be ok with you? @xresende @fernandohds564 @anacso17 ?

This involves installing octave (which is trivial), but also EPICA mca, which requires some custom modifications, but it shouldn't be too hard.

**Comment by fernandohds564** [comment]
It is fine by me, @lerwys !

**Comment by lerwys** [comment]
This will be implemented through separate role for easier maintenance

**Comment by lerwys** [comment]
This was done via PR #34 #35 #38
