### ISSUE TITLE
review NTP client configuration

### ISSUE THREAD

**Issue by xresende** [lnls-sirius/lnls-ansible#229]
see https://github.com/lnls-sirius/lnls-ansible/pull/227/files

**Comment by xresende** [comment]
Should we use 'poll' instead of 'server' ?
are minpoll:3 and maxpoll:3 too aggressive ?

**Comment by carneirofc** [comment]
We are not going to setup a NTP pool for the foreseeable future.
I think it is fine to keep these settings especially considering the low volume of clients we are attending.
