### ISSUE TITLE
Update tzdata package on role lnls-ans-role-ntp

### ISSUE THREAD

**Issue by carneirofc** [lnls-sirius/lnls-ansible#249]
We should consider updating the tz database of the target host. I think it makes sense specially considering that if the tzdata package is out of date the time will be messed up. Think as grouping the system time concern and not only the installation of the ntp client.

**Comment by lerwys** [comment]
I think this was already being done by `lnls-ans-role-ntp`, but I think we still need to change `present` to `latest` here: https://github.com/lnls-sirius/lnls-ansible/blob/master/roles/lnls-ans-role-ntp/tasks/main.yml#L39

**Comment by carneirofc** [comment]
We will have to change it. Currently we are just making sure that some tzdata package is installed. From the docs we have [`You can use other states like latest ONLY if they are supported by the underlying package module(s) executed.`](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/package_module.html)

**Comment by lerwys** [comment]
Yeah. I think it's all good then.
