### ISSUE TITLE
Move hosts, group_vars and host_vars to an inventory dir

### ISSUE THREAD

**Issue by carneirofc** [lnls-sirius/lnls-ansible#253]
The root directory is becoming too poluted.

As time goes by, the `hosts` file is tending to increase and will slowly become too much (maybe already is).
One pattern we could use is to create an `inventory` dir and move the `hosts`, `group_vars` and `host_vars`.

We can also go a little further and add subdirectories such as:

```bash
./inventory/servers/
./inventory/workstations/
...
```
If we decide to move and use Ansible Tower (aka. [AWX](https://github.com/ansible/awx)) this pattern will be usefull when creating jobs).

**Comment by carneirofc** [comment]
If we are going  to use this repo for things other than the control rooms workstations setup we should adopt this structure.
For example, I don't think it makes any sense to have random csstudio variables set when I am trying to configure a server that will have gluster and docker installed.
Information about the modules that some ide is using should not be polluting the all variables space.

**Comment by lerwys** [comment]
I like the idea of separating inventories. 

Initially, this repo was to be used only for configuring control room workstations, so it made sense to keep everything together, but it grew in scope and more things were just added. 

So, totally up for this.
