### ISSUE TITLE
Base Makefile too large

### ISSUE THREAD

**Issue by carneirofc** [lnls-sirius/lnls-ansible#254]
The initial Makefile is really large and have multiple responsibilities such as including other makefiles, config and run tests and run different types of playbooks.
I propose we turn it into a simple entrypoint for the project, moving the molecule related actions as well as some playbooks executions to differents files and import them.
We could also move those auxiliary makefiles to an specific folder in order to keep things clean.

**Comment by carneirofc** [comment]
Relative to the usage of makefiles, as long as we are using this repository via the cli they will be usefull.
There are some platforms such as AWX that I think we could use and be more productive, but this will take some time to setup and we should discuss it a little more about the scope of this repository and if this is a good way forward.

**Comment by lerwys** [comment]
I tend to agree with what you said, but I consider the ability to be able to config, run tests, and run playbooks through a simple Makefile (or any other point of entry) as a feature.

The molecule actions are just 10 lines of the Makefile and the only playbook actions that are not in other makefiles occupies 30 lines. I guess it would make sense to move the playbook actions to other makefiles, as you proposed, if we do #252, as well.

I only fear that by propagating makefiles to keep things separate we might end up complicating things more than simplifying, but I think it's worth a shot.

I think @xresende and @fernandohds564 are the ones that most use the Makefile targets. Any opinions?

**Comment by fernandohds564** [comment]
Hi guys, I think I don't understand the problem well enough to give opinions about it. I think you have more knowledge to define these methods and you are the ones who will work with it more often. As long as we have a course on how to run ansible for our day-to-day problems and you are available to answer some newbie questions, I don't see a problem in changing the organization of the repo!

Thanks for asking, though, @lerwys !

**Comment by xresende** [comment]
I might not have understood the proposal, but I think it is really useful to have all ansible actions as makefile targets, accesible via cli argument completion. we make use of it all the time. It is desirable to keep this feature, in my point of view. now, regarding how these targets are organized into files and folders, I do not have strong opinion.

**Comment by carneirofc** [comment]
I am not proposing to abandon the Makefile system, but to separate the concerns.
For example, lets supose I want to manage docker services using ansible, so i would have to create a number of playbooks and add targets for each playbook.
Now considering that i wish to configure a set o servers or even build/update docker images for specific services etc., the same steps will apply:
1. Add roles if needed
2. Create playbooks
3. Add a Makefile target

Now if those changes are happening in a single Makefile, we will have partially/completely unrelated targets. A single pull request will have a larger change to break something unrelated and as the file grows, the readability decreases etc.

**Comment by lerwys** [comment]
We can give it a try at your proposal @carneirofc. Sounds appealing. =]
